import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const challenges = [
  // WATER
  { title: '5-minute shower', category: 'WATER', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'Limit your shower to 5 minutes today. A typical shower uses 8–10 litres per minute — cutting it saves up to 50 litres.', instructions: ['Set a 5-minute timer before you step in', 'Turn off the water while soaping up', 'Step out as soon as the timer goes'], impactEstimate: { co2: 0.2, water: 50, waste: 0 }, educationalText: 'Hot water heating accounts for around 18% of home energy use. Shorter showers cut both water and energy bills.', tips: ['Use a waterproof phone timer', 'Try a shower playlist — pick one song'], barriers: ['Rushing in the morning', 'Hard to track time'], region: 'global' },
  { title: 'Fix a dripping tap', category: 'WATER', difficulty: 2, timeEstimate: 20, costLevel: 'low', description: 'A dripping tap wastes up to 20 litres a day. Fix it — or report it to your landlord — today.', instructions: ['Turn off the water supply under the sink', 'Replace the washer or cartridge', 'Test and confirm no drip'], impactEstimate: { co2: 0.1, water: 20, waste: 0 }, educationalText: 'A single dripping tap wastes about 7,000 litres per year — enough to fill 35 bathtubs.', tips: ['Most fixes cost under $5 at a hardware store', 'YouTube tutorials cover every tap type'], barriers: ['Not comfortable with DIY'], region: 'global' },
  { title: 'Drink tap water today', category: 'WATER', difficulty: 1, timeEstimate: 1, costLevel: 'free', description: 'Skip bottled water and refill a reusable bottle from the tap all day.', instructions: ['Fill a 1-litre reusable bottle at home', 'Refill it wherever tap water is available', 'Track how many times you refill'], impactEstimate: { co2: 0.3, water: 0, waste: 0.05 }, educationalText: 'Producing one plastic bottle emits about 100g of CO₂ before it reaches a shelf. Tap water in most developed countries is equally safe.', tips: ['Add a slice of lemon if you dislike the taste', 'Filter jugs improve taste inexpensively'], barriers: ['Taste preference', 'Availability at work'], region: 'global' },

  // FOOD
  { title: 'Plant-based meal', category: 'FOOD', difficulty: 2, timeEstimate: 30, costLevel: 'low', description: 'Cook one fully plant-based meal today — no meat, no dairy.', instructions: ['Pick a recipe using legumes, grains, or vegetables', 'Check you have all ingredients', 'Cook and enjoy — note how it tasted'], impactEstimate: { co2: 1.5, water: 200, waste: 0 }, educationalText: 'Beef produces about 27kg of CO₂ per kg. An equivalent lentil dish produces under 1kg — an 18× difference.', tips: ['Lentil bolognese, chickpea curry, or veggie stir-fry are simple starts', 'Season generously — spices are the secret'], barriers: ['Unsure what to cook', 'Family preferences'], region: 'global' },
  { title: 'No food waste today', category: 'FOOD', difficulty: 2, timeEstimate: 10, costLevel: 'free', description: 'Use up leftovers and odds-and-ends in your fridge. Throw nothing edible away today.', instructions: ['Check your fridge and pantry before cooking', 'Plan a meal around what needs using', 'Freeze anything you won\'t use in the next 2 days'], impactEstimate: { co2: 0.8, water: 100, waste: 0.1 }, educationalText: 'One-third of all food produced globally is wasted, accounting for 8% of greenhouse gas emissions.', tips: ['Soup and fried rice are great fridge-clear-out meals', 'Label leftovers with the date'], barriers: ['Creative block on how to combine ingredients'], region: 'global' },
  { title: 'Buy local produce', category: 'FOOD', difficulty: 1, timeEstimate: 30, costLevel: 'low', description: 'Buy at least one item from a local farmer\'s market, farm shop, or local grocer today.', instructions: ['Find your nearest market or local shop', 'Choose at least one seasonal, locally grown item', 'Ask the seller where it was grown'], impactEstimate: { co2: 0.5, water: 0, waste: 0 }, educationalText: 'Food typically travels 1,500–2,500km before reaching your plate. Local produce cuts transport emissions and often uses less packaging.', tips: ['Seasonal veg is usually cheaper at local markets', 'Root vegetables and leafy greens are easy local finds'], barriers: ['No market nearby', 'Cost concern'], region: 'global' },
  { title: 'Meatless Monday', category: 'FOOD', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'Go the entire day without eating meat — make it your regular Meatless Monday.', instructions: ['Plan your three meals in advance', 'Swap meat with beans, tofu, eggs, or cheese', 'Share what you ate with someone to inspire them'], impactEstimate: { co2: 2.0, water: 300, waste: 0 }, educationalText: 'If everyone in a city of 1 million went meat-free one day a week, it would be equivalent to taking 90,000 cars off the road annually.', tips: ['Egg fried rice, veggie pasta, or a bean wrap are quick wins', 'Don\'t skip protein — beans and eggs keep you full'], barriers: ['Habit', 'Family pressure'], region: 'global' },

  // ENERGY
  { title: 'Unplug standby devices', category: 'ENERGY', difficulty: 1, timeEstimate: 10, costLevel: 'free', description: 'Unplug or switch off at the wall every device on standby: TVs, phone chargers, gaming consoles.', instructions: ['Walk through every room with a notepad', 'Identify all plugged-in devices not in use', 'Unplug or use a power strip to turn them all off'], impactEstimate: { co2: 0.5, water: 0, waste: 0 }, educationalText: 'Standby power accounts for up to 10% of household electricity use. "Vampire draw" costs the average household $100–$200 per year.', tips: ['Smart plugs can automate this — set them to cut power at night', 'Phone chargers draw power even when no phone is connected'], barriers: ['Hard to remember', 'Awkward plugs behind furniture'], region: 'global' },
  { title: 'Cold wash laundry', category: 'ENERGY', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'Run your washing machine on a cold cycle (30°C or below) instead of a warm or hot wash.', instructions: ['Sort your laundry as normal', 'Select the cold or 30°C programme', 'Use a detergent designed for cold water'], impactEstimate: { co2: 0.6, water: 0, waste: 0 }, educationalText: 'About 90% of the energy a washing machine uses goes solely to heating water. Cold cycles clean clothes just as effectively for everyday loads.', tips: ['Modern detergents are formulated for cold water', 'Reserve hot washes for bedding and heavily soiled items'], barriers: ['Worry about cleanliness', 'Old machine without cold setting'], region: 'global' },
  { title: 'LED bulb swap', category: 'ENERGY', difficulty: 1, timeEstimate: 15, costLevel: 'low', description: 'Replace at least one incandescent or halogen bulb with an LED equivalent today.', instructions: ['Identify the highest-use light in your home', 'Buy an LED equivalent (same fitting, similar brightness)', 'Swap it out and dispose of the old bulb correctly'], impactEstimate: { co2: 40, water: 0, waste: 0 }, educationalText: 'LEDs use 75–80% less energy than incandescent bulbs and last 15–25× longer, saving roughly $55 per bulb over its lifetime.', tips: ['Check the lumens (brightness), not just the wattage', 'Warm-white LEDs (2700K) feel similar to old incandescents'], barriers: ['Upfront cost', 'Not sure which bulb to buy'], region: 'global' },
  { title: 'Air-dry your laundry', category: 'ENERGY', difficulty: 1, timeEstimate: 10, costLevel: 'free', description: 'Skip the tumble dryer today and hang your clothes to air-dry instead.', instructions: ['Do a load of laundry as normal', 'Set up a drying rack or use a clothesline', 'Spread items out to dry evenly'], impactEstimate: { co2: 1.8, water: 0, waste: 0 }, educationalText: 'Tumble dryers are among the most energy-hungry home appliances. Air-drying one full load saves around 1.8kg of CO₂ and extends the life of your clothes.', tips: ['Dry outside on sunny days for best results', 'A small fan can speed up indoor drying'], barriers: ['No outdoor space', 'Takes longer'], region: 'global' },

  // TRANSPORT
  { title: 'Walk or cycle one trip', category: 'TRANSPORT', difficulty: 1, timeEstimate: 20, costLevel: 'free', description: 'Replace one car or taxi journey today with walking or cycling — however short.', instructions: ['Identify one trip you would normally drive', 'Check the walking or cycling time (often less than you think)', 'Walk or cycle that journey today'], impactEstimate: { co2: 1.2, water: 0, waste: 0 }, educationalText: 'Short car trips under 5km are disproportionately polluting — the engine never reaches operating temperature, burning more fuel per km.', tips: ['Use Google Maps cycling mode to find safe routes', 'If it\'s raining, pack a light rain jacket rather than skipping'], barriers: ['Safety concerns', 'Too far', 'Weather'], region: 'global' },
  { title: 'Take public transport', category: 'TRANSPORT', difficulty: 1, timeEstimate: 30, costLevel: 'low', description: 'Use a bus, tram, train, or metro for at least one journey you would normally drive.', instructions: ['Plan your route on a public transport app', 'Buy a ticket or tap your card', 'Note the time difference vs driving — it\'s often minimal'], impactEstimate: { co2: 2.5, water: 0, waste: 0 }, educationalText: 'A full bus produces about 20× less CO₂ per passenger than a single-occupancy car. A commuter train can be 50× cleaner.', tips: ['Download the local transit app and set up a top-up card', 'Use the time to read, listen, or just rest'], barriers: ['Infrequent service', 'Longer journey time'], region: 'global' },
  { title: 'Work from home today', category: 'TRANSPORT', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'If you can, avoid commuting entirely by working remotely for one day.', instructions: ['Let your manager know (if required)', 'Set up your home workspace properly', 'Log your commute carbon saving'], impactEstimate: { co2: 4.0, water: 0, waste: 0 }, educationalText: 'The average commuter emits about 4kg of CO₂ per day driving to work. One remote day per week cuts annual commuting emissions by 20%.', tips: ['Designate a specific workspace to stay productive', 'Use the time you save on a walk or workout'], barriers: ['Job requires physical presence', 'Manager won\'t allow it'], region: 'global' },
  { title: 'Carpool this week', category: 'TRANSPORT', difficulty: 2, timeEstimate: 15, costLevel: 'free', description: 'Arrange to share a car journey with at least one other person who\'s going the same direction.', instructions: ['Identify a colleague, neighbour, or friend who makes a similar journey', 'Message them today to arrange a carpool', 'Agree on a pickup point and time'], impactEstimate: { co2: 3.0, water: 0, waste: 0 }, educationalText: 'If every car in a city of 1 million carried just one extra passenger, it would remove the equivalent of 250,000 cars from the road.', tips: ['BlaBlaCar or Waze Carpool can connect you with strangers going the same way', 'Share fuel costs to make it fair'], barriers: ['Timing differences', 'Comfort with strangers'], region: 'global' },

  // WASTE
  { title: 'Refuse a plastic bag', category: 'WASTE', difficulty: 1, timeEstimate: 1, costLevel: 'free', description: 'Carry a reusable bag today and decline any plastic bags offered to you.', instructions: ['Put a foldable tote in your bag or pocket', 'When offered a plastic bag, say "no thanks — I have one"', 'Use it for every purchase today'], impactEstimate: { co2: 0.1, water: 0, waste: 0.01 }, educationalText: 'The average plastic bag is used for just 12 minutes but takes up to 1,000 years to decompose. The UK alone uses 9.9 billion per year.', tips: ['Keep a spare bag in every bag you own so you\'re never caught short', 'Compact bags the size of a wallet are easy to carry'], barriers: ['Forgot the bag', 'Unexpected shopping'], region: 'global' },
  { title: 'Compost food scraps', category: 'WASTE', difficulty: 2, timeEstimate: 10, costLevel: 'free', description: 'Start or contribute to a compost bin with today\'s food scraps — peels, cores, and coffee grounds.', instructions: ['Gather fruit and veg scraps, coffee grounds, and eggshells', 'Add them to a compost bin, food waste caddy, or a neighbour\'s compost', 'Keep meat, dairy, and cooked food out of home compost'], impactEstimate: { co2: 0.4, water: 0, waste: 0.2 }, educationalText: 'When food waste goes to landfill, it produces methane — a greenhouse gas 80× more potent than CO₂ over 20 years. Composting prevents this.', tips: ['A small caddy under the sink makes it easy to collect scraps as you cook', 'Many councils collect food waste — check yours'], barriers: ['No garden', 'Worried about smell'], region: 'global' },
  { title: 'Recycle correctly today', category: 'WASTE', difficulty: 1, timeEstimate: 10, costLevel: 'free', description: 'Spend 10 minutes learning what your local service actually accepts and sort this week\'s recycling correctly.', instructions: ['Search "[your council] recycling guide"', 'Sort your current recycling bin against the guide', 'Remove any items that don\'t belong (wish-cycling)'], impactEstimate: { co2: 0.3, water: 0, waste: 0.5 }, educationalText: '"Wish-cycling" — putting items in recycling just in case — actually contaminates loads and sends whole batches to landfill. When in doubt, leave it out.', tips: ['Rinse containers — food residue is the top cause of contamination', 'Takeaway coffee cups are usually NOT recyclable (plastic-lined)'], barriers: ['Confusing local rules', 'Time'], region: 'global' },
  { title: 'Buy second-hand today', category: 'WASTE', difficulty: 2, timeEstimate: 30, costLevel: 'free', description: 'Before buying anything new today, check if you can find it second-hand first.', instructions: ['Think of something you need or want to buy', 'Search eBay, Facebook Marketplace, Vinted, or a charity shop', 'If you find it, buy second-hand; if not, note the search'], impactEstimate: { co2: 2.0, water: 0, waste: 0.5 }, educationalText: 'Extending the life of a garment by 9 months reduces its carbon, water, and waste footprint by 20–30%. The same principle applies to furniture, electronics, and books.', tips: ['Charity shops often have excellent quality at low cost', 'Vinted and Depop are great for clothing'], barriers: ['Not knowing where to look', 'Hygiene concerns with some items'], region: 'global' },

  // CONSUMPTION
  { title: 'Digital-only purchases today', category: 'CONSUMPTION', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'For any media you would buy today — a book, film, or music — choose a digital version instead of physical.', instructions: ['Before buying anything physical today, ask if there\'s a digital option', 'Use an e-book, streaming, or download instead', 'Cancel any unnecessary physical subscriptions'], impactEstimate: { co2: 0.5, water: 0, waste: 0.1 }, educationalText: 'A single paperback book requires about 3kg of wood and 1kg of CO₂ to produce. Digital books have a much smaller footprint when shared across readers.', tips: ['Your local library likely has a free e-book service (Libby, BorrowBox)', 'Spotify or YouTube Music replaces physical CDs'], barriers: ['Prefer physical feel', 'Screen fatigue'], region: 'global' },
  { title: '24-hour no-spend challenge', category: 'CONSUMPTION', difficulty: 2, timeEstimate: 5, costLevel: 'free', description: 'Spend nothing today except on absolute necessities. No takeaway, no online shopping, no impulse buys.', instructions: ['Remove shopping apps from your home screen for the day', 'Eat what\'s already in your fridge and cupboard', 'If you feel the urge to buy, write it down and revisit tomorrow'], impactEstimate: { co2: 1.0, water: 0, waste: 0.3 }, educationalText: 'Impulse purchases account for 40–80% of all retail spending. A 24-hour pause often reveals which purchases were wants vs needs.', tips: ['Plan meals from pantry staples the night before', 'Keep a "want list" — items still on it after a week may be worth buying'], barriers: ['Habit', 'Social occasions'], region: 'global' },

  // BIODIVERSITY
  { title: 'Identify a wild plant or bird', category: 'BIODIVERSITY', difficulty: 1, timeEstimate: 15, costLevel: 'free', description: 'Use iNaturalist or a similar app to identify one wild plant, bird, or insect you encounter today.', instructions: ['Download iNaturalist (free)', 'Photograph a plant, bird, or insect you don\'t recognise', 'Submit the photo and read about the species'], impactEstimate: { co2: 0, water: 0, waste: 0 }, educationalText: 'Citizen science data from apps like iNaturalist has contributed to over 3,000 peer-reviewed scientific papers on biodiversity and conservation.', tips: ['Gardens, parks, and even cracks in pavement have fascinating species', 'The Merlin app by Cornell is excellent for bird ID by sound'], barriers: ['No green space nearby', 'Unsure how to use the app'], region: 'global' },
  { title: 'Plant something', category: 'BIODIVERSITY', difficulty: 2, timeEstimate: 30, costLevel: 'low', description: 'Plant a seed, seedling, or cutting today — in a pot, garden bed, or community garden.', instructions: ['Choose a plant suited to your space (herbs work indoors)', 'Prepare the soil or pot and plant it correctly', 'Water it and put it somewhere appropriate'], impactEstimate: { co2: 0.1, water: 0, waste: 0 }, educationalText: 'Urban plants reduce local temperatures by 1–8°C through shading and evapotranspiration, reducing energy demand for cooling and improving air quality.', tips: ['Basil, mint, and chillies grow easily in small pots', 'Free seed swaps happen at many libraries and community centres'], barriers: ['No outdoor space', 'No money for plants or soil'], region: 'global' },

  // COMMUNITY
  { title: 'Share a tip with a friend', category: 'COMMUNITY', difficulty: 1, timeEstimate: 5, costLevel: 'free', description: 'Send one practical sustainability tip to a friend or family member today.', instructions: ['Think of one habit that has made a real difference for you', 'Send a message — text, email, or chat', 'Keep it positive, not preachy — share what works for you'], impactEstimate: { co2: 0, water: 0, waste: 0 }, educationalText: 'Social norms are one of the most powerful drivers of behaviour change. A personal recommendation is far more effective than an advertisement or government campaign.', tips: ['Focus on tips that save money too — those land better', 'A photo or short video is more engaging than plain text'], barriers: ['Not wanting to seem preachy', 'Not sure what tip to share'], region: 'global' },
  { title: 'Join a local clean-up', category: 'COMMUNITY', difficulty: 2, timeEstimate: 120, costLevel: 'free', description: 'Sign up for or organise a local litter pick or community clean-up event.', instructions: ['Search "litter pick [your area]" or check Keep Britain Tidy / local Facebook groups', 'Sign up and note the date and location', 'If none is nearby, organise one with 3 or more neighbours'], impactEstimate: { co2: 0, water: 0, waste: 2.0 }, educationalText: 'Litter that reaches waterways kills an estimated 1 million sea birds and 100,000 marine mammals annually. Local clean-ups directly prevent this.', tips: ['Many councils provide free litter-picking equipment', 'Even 30 minutes solo on your street counts'], barriers: ['Time commitment', 'Social anxiety'], region: 'global' },

  // WELLBEING
  { title: 'Spend 30 minutes in nature', category: 'WELLBEING', difficulty: 1, timeEstimate: 30, costLevel: 'free', description: 'Go outside and spend 30 uninterrupted minutes in a green or natural space — phone in pocket.', instructions: ['Walk to the nearest park, garden, woodland, or beach', 'Leave your phone in your pocket for the full 30 minutes', 'Notice what you see, hear, and smell'], impactEstimate: { co2: 0, water: 0, waste: 0 }, educationalText: 'Studies show that 120 minutes per week in nature significantly improves self-reported health and wellbeing. Just 20 minutes outdoors lowers cortisol (stress hormone) levels.', tips: ['Early mornings in parks are quieter and full of birdsong', 'You don\'t need countryside — an urban park or garden counts'], barriers: ['Weather', 'No green space nearby', 'Time'], region: 'global' },
]

async function main() {
  console.log('Seeding challenges...')

  await prisma.challenge.deleteMany({})

  for (const c of challenges) {
    await prisma.challenge.create({
      data: {
        title:           c.title,
        category:        c.category as any,
        difficulty:      c.difficulty,
        timeEstimate:    c.timeEstimate,
        costLevel:       c.costLevel,
        description:     c.description,
        instructions:    c.instructions,
        impactEstimate:  c.impactEstimate,
        educationalText: c.educationalText,
        tips:            c.tips,
        barriers:        c.barriers,
        region:          c.region,
        isActive:        true,
      }
    })
  }

  console.log(`Seeded ${challenges.length} challenges.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
